### ISSUE TITLE
structure:true without aria attributes

### ISSUE THREAD

**Issue by pkra** [Speech-Rule-Engine/speech-rule-engine#690]
It would be very helpful not to have it simultaneously to allow the exploration of other patterns. It also avoids having to clean up the attributes to work around SRE idiosyncrasies.

**Comment by zorkow** [comment]
For clarification: You want the `skeleton` attribute only, without any other aria annotations (like `owns`)?

**Comment by pkra** [comment]
> For clarification: You want the `skeleton` attribute only, without any other aria annotations (like `owns`)?

Sorry, I used the wrong terminology -- I'll update the title. 

No, I don't want a skeleton attribute. 

I'm looking for whatever the `structure: true,` settgin was producing before the recent addition of `aria-*` and `role` attributes -- IIRC those were just `data-semantic-*` attributes but maybe I'm missing something.

From a quick look through recent commits, I'm guessing I'm looking to disable`addAria` from fadf19d6bd55ed3a1f1e8b7b53df7078c8d97713. (The generated aria stuff is also problematic in itself but that's a separate issue).

**Comment by zorkow** [comment]
That's what I meant. And I probably knew that this issue was coming when I opted against YAO... 
But I can hide it behind YAO! No problem, but I am running out of letters. Any suggestions?

**Comment by pkra** [comment]
> Any suggestions?

I'd say stop using ARIA attributes. 

First, I think ARIA markup belongs on the mathjax end of things - they determine user facing behavior which is not what SRE usually provides. 

Second, they are weirdly implemented; you seem to have followed my advice half-way with problematic results (both here and in the client-side walker). 

Third, developers (like myself) who want to use alternative patterns now have to remove these first which is cumbersome and risks dropping actually useful information.

**Comment by klobetime** [comment]
ARIA does provide user-facing behavior, but arguably so does SRE -- the entire point of generating speech from math is to present it to the user in some fashion. I agree that ARIA can be problematic, but removing it entirely seems overkill. At the very least, `aria-label` is _extremely_ useful in correcting issues that can't/shouldn't be corrected in other ways, such as in #632.

Not sure that @pkra was actually advocating removing everything ARIA related rather than hiding behind a flag, but wanted to make this point just in case. :)

**Comment by pkra** [comment]
> Not sure that @pkra was actually advocating removing everything ARIA related rather than hiding behind a flag, but wanted to make this point just in case. :)

I see how this might have been confusing. To hopefully clarify: I requested that the option `structure:true` goes back to its old behavior - not adding any ARIA attributes. (SREs enrichment output is then still present in the output using data-semantic-* attributes.) 

To explain again: the ARIA markup currently produced with this option is invalid and forces authors into a very specific ARIA pattern. Neither seems like a good idea.

(I realize now that #632 appears to be about input, not output so I may have misunderstood your point entirely.)

**Comment by zorkow** [comment]
PR #706 adds a new flag `aria` which is set to `false` by default. So you should no longer see the aria attributes.
